config/routes.rb
Rails.application.routes.draw do
  resources :spotify_accounts

  root to: 'spotify_accounts#index'

  get '/auth/spotify/callback', to: 'spotify_accounts#spotify'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :spotify_account
end

app/models/spotify_account.rb
class SpotifyAccount < ActiveRecord::Base
  has_many :playlists

  validates :username, presence: true, uniqueness: true
  validates :display_name, presence: true
  validates :picture_url, presence: true
  validates :followers, presence: true
  validates :profile_url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spotify_accounts_controller.rb
class SpotifyAccountsController < ApplicationController
  before_action :set_spotify_account, only: [:show, :edit, :update, :destroy]

  # GET /spotify_accounts
  # GET /spotify_accounts.json
  def index
    @spotify_accounts = SpotifyAccount.all
  end

  def spotify
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    # Now you can access user's private data, create playlists and much more

    # Access private data
  end

  # GET /spotify_accounts/1
  # GET /spotify_accounts/1.json
  def show
  end

  # GET /spotify_accounts/new
  def new
    @spotify_account = SpotifyAccount.new
  end

  # GET /spotify_accounts/1/edit
  def edit
  end

  # POST /spotify_accounts
  # POST /spotify_accounts.json
  def create
    @spotify_account = SpotifyAccount.new(spotify_account_params)

    respond_to do |format|
      if @spotify_account.save
        format.html { redirect_to @spotify_account, notice: 'Spotify account was successfully created.' }
        format.json { render :show, status: :created, location: @spotify_account }
      else
        format.html { render :new }
        format.json { render json: @spotify_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spotify_accounts/1
  # PATCH/PUT /spotify_accounts/1.json
  def update
    respond_to do |format|
      if @spotify_account.update(spotify_account_params)
        format.html { redirect_to @spotify_account, notice: 'Spotify account was successfully updated.' }
        format.json { render :show, status: :ok, location: @spotify_account }
      else
        format.html { render :edit }
        format.json { render json: @spotify_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spotify_accounts/1
  # DELETE /spotify_accounts/1.json
  def destroy
    @spotify_account.destroy
    respond_to do |format|
      format.html { redirect_to spotify_accounts_url, notice: 'Spotify account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spotify_account
      @spotify_account = SpotifyAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spotify_account_params
      params[:spotify_account]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spotify_accounts_helper.rb
module SpotifyAccountsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpotifyBroadcasting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spotify_accounts/_form.html.erb
<%= form_for @spotify_account, :html => { :class => "form-horizontal spotify_account" } do |f| %>

  <% if @spotify_account.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@spotify_account.errors.count, "error") %> prohibited this spotify_account from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @spotify_account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                spotify_accounts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/spotify_accounts/edit.html.erb
<%- model_class = SpotifyAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/spotify_accounts/index.html.erb
<%- model_class = SpotifyAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @spotify_accounts.each do |spotify_account| %>
      <tr>
        <td><%= link_to spotify_account.id, spotify_account_path(spotify_account) %></td>
        <td><%=l spotify_account.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_spotify_account_path(spotify_account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      spotify_account_path(spotify_account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Sign in with Spotify', '/auth/spotify' %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_spotify_account_path,
            :class => 'btn btn-primary' %>

app/views/spotify_accounts/new.html.erb
<%- model_class = SpotifyAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/spotify_accounts/show.html.erb
<%- model_class = SpotifyAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              spotify_accounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_spotify_account_path(@spotify_account), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              spotify_account_path(@spotify_account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>